[general]
wiki_location = "~/wiki"
port = 6683
user = ""
pass = ""
version = "0.0.2"
# directory where images / pdfs / other files are stored
media_location = "~/wiki_media"
host = "http://localhost:6683"

[sync]
use_git = true
# time in seconds that tendril will try and sync changes to git
sync_interval = 60
# branch it will try and push to
branch = "main"
